version: '2.3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx
      - /var/www/nginx:/var/www/nginx
        # ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    mem_limit: 100m
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always

  show-scraper:
    image: metasyn/show-scraper
    expose:
      - "80"
    cpus: 0.1
    mem_limit: 10m

    #webdav:
    #image: bytemark/webdav
    #expose:
    #  - "80"
    #environment:
    #  SERVER_NAME: metasyn.pw
    #  LOCATION: /webdav
    #restart: always
    #volumes:
    #  - /var/lib/dav:/var/lib/dav
    #  - ./webdav.passwd:/user.passwd
