version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx
      - /var/www/nginx:/var/www/nginx
      - /var/log/nginx:/var/log/nginx
        # ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    shm_size: '256mb'

  show-scraper:
    image: metasyn/show-scraper
    expose:
      - "80"

  ##############
  # NEXTCLOUD #
  ##############

  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - nextcloud-db:/var/lib/mysql

  nextcloud:
    image: nextcloud:apache
    restart: always
    ports:
      - 80
    volumes:
      - nextcloud:/var/www
    environment:
      - MYSQL_HOST=nextcloud-db
    depends_on:
      - nextcloud-db


volumes:
  nextcloud:
  nextcloud-db:
